"project_id_env" : CROWDIN_PROJECT_ID
"api_token_env" : CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy" : true

"files": [
  {
    "source": "/en/*.md",
    "translation": "/intl/%two_letters_code%/%original_file_name%"
  },
  {
    "source": "/en/title.yml",
    "translation": "/intl/%two_letters_code%/%original_file_name%"
  }
]
